spring.application.name=order-service
server.port=8081
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Resilience4j Retry
resilience4j.retry.instances.orderServiceRetry.max-attempts=3
resilience4j.retry.instances.orderServiceRetry.wait-duration=500ms
resilience4j.retry.instances.orderServiceRetry.retry-exceptions[0]=feign.FeignException
resilience4j.retry.instances.orderServiceRetry.ignore-exceptions[0]=feign.FeignException.BadRequest
resilience4j.retry.instances.paymentClientRetry.ignore-exceptions[0]=feign.FeignException.BadRequest
resilience4j.retry.instances.paymentClientRetry.ignore-exceptions[1]=io.github.resilience4j.ratelimiter.RequestNotPermitted
resilience4j.retry.instances.paymentClientRetry.ignore-exceptions[2]=io.github.resilience4j.bulkhead.BulkheadFullException
# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.orderControllerCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.paymentClientCircuitBreaker.base-config=default
resilience4j.circuitbreaker.instances.paymentClientCircuitBreaker.record-exceptions[0]=feign.FeignException
resilience4j.circuitbreaker.instances.paymentClientCircuitBreaker.ignore-exceptions[0]=io.github.resilience4j.ratelimiter.RequestNotPermitted
resilience4j.circuitbreaker.instances.paymentClientCircuitBreaker.ignore-exceptions[1]=io.github.resilience4j.bulkhead.BulkheadFullException
# Resilience4j Rate Limiter
resilience4j.ratelimiter.instances.paymentClientRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.paymentClientRateLimiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.paymentClientRateLimiter.timeout-duration=500ms
# Resilience4j Bulkhead
resilience4j.bulkhead.instances.paymentClientBulkhead.max-concurrent-calls=10
resilience4j.bulkhead.instances.paymentClientBulkhead.max-wait-duration=0

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,retries,retryevents,ratelimiters,ratelimiterevents,bulkheads,bulkheadevents